# # Comments are provided throughout this file to help you get started.
# # If you need more help, visit the Docker Compose reference guide at
# # https://docs.docker.com/go/compose-spec-reference/

# # Here the instructions define your application as a service called "server".
# # This service is built from the Dockerfile in the current directory.
# # You can add other services your application may depend on here, such as a
# # database or a cache. For examples, see the Awesome Compose repository:
# # https://github.com/docker/awesome-compose
# services:
#   server:
#     build:
#       context: .
#     ports:
#       - 8000:8000

# # The commented out section below is an example of how to define a PostgreSQL
# # database that your application can use. `depends_on` tells Docker Compose to
# # start the database before your application. The `db-data` volume persists the
# # database data between container restarts. The `db-password` secret is used
# # to set the database password. You must create `db/password.txt` and add
# # a password of your choosing to it before running `docker compose up`.
# #     depends_on:
# #       db:
# #         condition: service_healthy
# #   db:
# #     image: postgres
# #     restart: always
# #     user: postgres
# #     secrets:
# #       - db-password
# #     volumes:
# #       - db-data:/var/lib/postgresql/data
# #     environment:
# #       - POSTGRES_DB=example
# #       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
# #     expose:
# #       - 5432
# #     healthcheck:
# #       test: [ "CMD", "pg_isready" ]
# #       interval: 10s
# #       timeout: 5s
# #       retries: 5
# # volumes:
# #   db-data:
# # secrets:
# #   db-password:
# #     file: db/password.txt
services:
  django:
    build: .
    container_name: task_manager-server
    command: gunicorn task_manager.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - .:/app  # useful for live code reload in development
    restart: always

  db:
    image: postgres:17
    container_name: task_manager-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  react:
    build:
      context: ./taskflow-manager
      dockerfile: Dockerfile
    container_name: task_manager-react
    ports:
      - "8080:80"
    depends_on:
      - django
    environment:
      - VITE_API_URL=http://django:8000/api

volumes:
  postgres_data:
  static_volume:
  media_volume:
